# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_tagline', models.CharField(max_length=200, null=True)),
                ('article_author', models.CharField(max_length=2000)),
                ('article_date', models.DateTimeField(verbose_name='date published')),
                ('article_text', models.TextField(blank=True, max_length=20000)),
                ('article_image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('heading1', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph1', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading2', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph2', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading3', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph3', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading4', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph4', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading5', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph5', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading6', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph6', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading7', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph7', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading8', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph8', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading9', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph9', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading10', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph10', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading11', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph11', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading12', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph12', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading13', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph13', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading14', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph14', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading15', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph15', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading16', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph16', models.TextField(blank=True, max_length=20000, null=True)),
                ('heading17', models.CharField(blank=True, max_length=250, null=True)),
                ('paragraph17', models.TextField(blank=True, max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LongArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, null=True)),
                ('article_tagline', models.CharField(max_length=200, null=True)),
                ('article_author', models.CharField(max_length=2000, null=True)),
                ('article_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('article_id', models.IntegerField(null=True)),
                ('article_text', models.TextField(max_length=20000, null=True)),
                ('article_image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('heading1', models.CharField(max_length=250, null=True)),
                ('paragraph1', models.TextField(max_length=20000, null=True)),
                ('heading2', models.CharField(max_length=250, null=True)),
                ('paragraph2', models.TextField(max_length=20000, null=True)),
                ('heading3', models.CharField(max_length=250, null=True)),
                ('paragraph3', models.TextField(max_length=20000, null=True)),
                ('heading4', models.CharField(max_length=250, null=True)),
                ('paragraph4', models.TextField(max_length=20000, null=True)),
                ('heading5', models.CharField(max_length=250, null=True)),
                ('paragraph5', models.TextField(max_length=20000, null=True)),
                ('heading6', models.CharField(max_length=250, null=True)),
                ('paragraph6', models.TextField(max_length=20000, null=True)),
                ('heading7', models.CharField(max_length=250, null=True)),
                ('paragraph7', models.TextField(max_length=20000, null=True)),
                ('heading8', models.CharField(max_length=250, null=True)),
                ('paragraph8', models.TextField(max_length=20000, null=True)),
                ('heading9', models.CharField(max_length=250, null=True)),
                ('paragraph9', models.TextField(max_length=20000, null=True)),
                ('heading10', models.CharField(max_length=250, null=True)),
                ('paragraph10', models.TextField(max_length=20000, null=True)),
                ('heading11', models.CharField(max_length=250, null=True)),
                ('paragraph11', models.TextField(max_length=20000, null=True)),
                ('heading12', models.CharField(max_length=250, null=True)),
                ('paragraph12', models.TextField(max_length=20000, null=True)),
                ('heading13', models.CharField(max_length=250, null=True)),
                ('paragraph13', models.TextField(max_length=20000, null=True)),
                ('heading14', models.CharField(max_length=250, null=True)),
                ('paragraph14', models.TextField(max_length=20000, null=True)),
                ('heading15', models.CharField(max_length=250, null=True)),
                ('paragraph15', models.TextField(max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='longarticle',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Metadata'),
        ),
        migrations.AddField(
            model_name='content',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Metadata'),
        ),
    ]
