# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='article_image2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
