# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20161023_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='metadata',
            field=models.ForeignKey(default=datetime.datetime(2016, 10, 23, 6, 24, 2, 791000, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='articles.Metadata'),
            preserve_default=False,
        ),
    ]
