# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_content_article_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
