# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_content_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Metadata'),
        ),
    ]
