# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_content_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='article_author',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='content',
            name='article_title',
            field=models.TextField(max_length=200),
        ),
    ]
