# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20161024_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='article_tagline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='article_text',
            field=models.TextField(max_length=20000),
        ),
    ]
