# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20161024_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='article_image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
