# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_content_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='article_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
