# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20161031_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='article_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
