# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20161031_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='article_content',
        ),
    ]
