# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_remove_content_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='column',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), null=True, size=None),
        ),
    ]
