# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20161031_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='column2',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name=models.TextField(blank=True, max_length=10000, null=True)),
        ),
    ]
