# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_auto_20161031_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='column2',
        ),
    ]
