# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_remove_content_column2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='column',
        ),
    ]
