# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20161101_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='content',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='content',
            name='heading3',
        ),
        migrations.RemoveField(
            model_name='content',
            name='heading4',
        ),
        migrations.RemoveField(
            model_name='content',
            name='heading5',
        ),
        migrations.RemoveField(
            model_name='content',
            name='paragraph1',
        ),
        migrations.RemoveField(
            model_name='content',
            name='paragraph2',
        ),
        migrations.RemoveField(
            model_name='content',
            name='paragraph3',
        ),
        migrations.RemoveField(
            model_name='content',
            name='paragraph4',
        ),
        migrations.RemoveField(
            model_name='content',
            name='paragraph5',
        ),
    ]
