# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_auto_20161101_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=250, null=True)),
                ('paragraph1', models.TextField(max_length=20000, null=True)),
                ('heading2', models.CharField(max_length=250, null=True)),
                ('paragraph2', models.TextField(max_length=20000, null=True)),
                ('heading3', models.CharField(max_length=250, null=True)),
                ('paragraph3', models.TextField(max_length=20000, null=True)),
                ('heading4', models.CharField(max_length=250, null=True)),
                ('paragraph4', models.TextField(max_length=20000, null=True)),
                ('heading5', models.CharField(max_length=250, null=True)),
                ('paragraph5', models.TextField(max_length=20000, null=True)),
                ('heading6', models.CharField(max_length=250, null=True)),
                ('paragraph6', models.TextField(max_length=20000, null=True)),
                ('heading7', models.CharField(max_length=250, null=True)),
                ('paragraph7', models.TextField(max_length=20000, null=True)),
                ('heading8', models.CharField(max_length=250, null=True)),
                ('paragraph8', models.TextField(max_length=20000, null=True)),
                ('heading9', models.CharField(max_length=250, null=True)),
                ('paragraph9', models.TextField(max_length=20000, null=True)),
                ('heading10', models.CharField(max_length=250, null=True)),
                ('paragraph10', models.TextField(max_length=20000, null=True)),
                ('heading11', models.CharField(max_length=250, null=True)),
                ('paragraph11', models.TextField(max_length=20000, null=True)),
                ('heading12', models.CharField(max_length=250, null=True)),
                ('paragraph12', models.TextField(max_length=20000, null=True)),
                ('heading13', models.CharField(max_length=250, null=True)),
                ('paragraph13', models.TextField(max_length=20000, null=True)),
                ('heading14', models.CharField(max_length=250, null=True)),
                ('paragraph14', models.TextField(max_length=20000, null=True)),
                ('heading15', models.CharField(max_length=250, null=True)),
                ('paragraph15', models.TextField(max_length=20000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='longArticle',
            field=models.ManyToManyField(to='articles.LongArticle'),
        ),
    ]
