# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_auto_20161101_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='longarticle',
            name='article_author',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='longarticle',
            name='article_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='longarticle',
            name='article_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='longarticle',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='longarticle',
            name='article_tagline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='longarticle',
            name='article_text',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='longarticle',
            name='article_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='longarticle',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Metadata'),
        ),
    ]
