# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_auto_20161101_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='heading10',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading11',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading12',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading13',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading14',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading15',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading6',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading7',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading8',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='heading9',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph10',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph11',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph12',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph13',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph14',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph15',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph6',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph7',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph8',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='paragraph9',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
