# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0040_auto_20161106_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
