# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0043_auto_20161106_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='metadata',
        ),
    ]
